hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "904365e7891802e522e5a35189b7039e18f56a22ab30bd99af59b97ec4b7468e"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "8e03a359dfe4257c9cade378e8c29c981b168ceb0a34838b296a917331ee8a28"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "5d264a16b0269d4c847ab974ea6b93555af6b56f5530be54a45406dc55c8d2b2"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "2d58b7783694c38d8264f263b9ee1f8b31c1aa9dd98866deb20719b252dc4b47"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "9854603f767980c514aefe9c391a6d3fa89dc6be18d23ab462f2a3bbabe7652c"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "36cbe6941b0b16bc140e0465ac1654f7b4b45a826ba53d8bc455e73c9546ca7a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f0df50d90dcff14610db52172bb56b6278e43964d18fae0853239dae905d4398"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c695e069bb050497dc9d262b4ebb19e20efa879d21c51f61780420ce5ab40a90"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "b80e42354a7ed541e92506e96204ca425dd22dc55c3cef5dcc161b3c487fee59"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7a2991786a3523846ee1dcaa4c34c9f1d7a544ea4dbf252df8482b19549009b4"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6085d2f0a5deabc026667492ac344d9b9007c80ccadb3f916fe9b0ec3037f022"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "d53890cf52063bca46d312c75428acd1e8c754cbb23bb639e0f04a562556cfe3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fcf5aeb5a41fadabd7274196fed4a5e9e3a95cec5de9a3dfea889131576c4320"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4df808c299fd18fd57b6f9f1997d89cdcbcbddf3472136b067a57979969af04e"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "ee8cbde93306796c1a4a3535672b364c27a1eebd75185838c7961cc2895027a0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "831a82763a6dfcdc3ec08c4dd387f12efa09c986e0c2ff48c500c4333038288a"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "072e68890c158e923da65e4a07ad849ee4eed71f4178b56979699d4d2e31c4e3"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "2ea99e3bd447fafb450a643e064816457b9c2a48c1786b51047ec3d5f2ec2a62"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f529ec107b8cb4cacf8da77e65e1864789d8710d22f6c4cfa3265aaab7fe8aba"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "93e5023b9b45c297a69ee769941b4c6a7f65eeb3f2baa569ad52f3d5aa8de398"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "da8027302e071db16b21c4abf1ab8f04245b283c4f44a3fdf98dc1e4c6d2d585"
metafile = true

[[files]]
file = "mods/resource-pack-overrides.pw.toml"
hash = "85a5ed322f547de3413ed6944f2a09ab53abb6db323f00c42ee13c6e2f391fb4"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "f32e1db7fd9d5c5677b32c07d8161ae94e1d6ee31f7093df35e012c99f569491"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "8883c9d38f7da2907ed206e7c9dab0cd52e0226f346215642d87bd03a7e1440c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d8e1c8d570cb19aafa17aa9e98a4c6c683853fec2c9cf58e89660ce4e2ad51ba"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "b01870e848aee7e1a2e19c6530bdd4c479b21a2f6f67134da75210844252d48f"
metafile = true

[[files]]
file = "mods/tab-was-taken.pw.toml"
hash = "4c21dc77628c934d4657eae1b13a78969c4e953abfd05b5161f5a3c9f082be96"
metafile = true

[[files]]
file = "resourcepacks/detailed-animations.pw.toml"
hash = "906e24b906e3814053d3c83ee03722a14daffd139db9771c14aec6f086b7f40d"
metafile = true

[[files]]
file = "resourcepacks/theones-eating-animation-pack.pw.toml"
hash = "4de101c76fdb36e502852b74de62b64b6221f65819ba1a0de7ac074f3f450e0a"
metafile = true
