name = "MyServerPack"
author = "Tee"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e19cfa80300e9134bd09af4756afe06f336ad510f1970e8de061b6abdbd110a5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
